image: node:latest

cache:
  paths:
   - node_modules/

before_script:
  - npm install

stages:
  - test
  - deploy

test:
  stage: test
  script: npm run test

deploy:
  stage: deploy
  environment:
    name: production
  only:
   - master
  script:
   - npm run deploy-initial
